stages:
  - Image Copy
  - Image Scan


include:
#  - project: 'DSO/DASTScanner'
#    file: '.gitlab-ci.yml'
  - remote: 'https://gitlab.com/prismacloud-public/shift-left/extension/-/raw/master/.pcs.gitlab-ci.yml'


variables:
  wb_api_ghcr_tag: $WB_API_TAG  # GHCR tag, env var set in Gitlab Variables
  wb_redis_ghcr_tag: $WB_REDIS_TAG  # GHCR tag, env var set in Gitlab Variables
  wb_localstack_ghcr_tag: $WB_LOCALSTACK_TAG # GHCR tag, env var set in Gitlab Variables


CopyDevImages:
  stage: Image Copy
  tags:
    - qed-stg-runner
  when: manual
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [ "" ]
  script:
    - crane auth login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - crane copy "ghcr.io/quanted/wb-api:$wb_api_ghcr_tag" "$CI_REGISTRY_IMAGE/wb-api:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    - crane copy "ghcr.io/quanted/wb-redis:$wb_redis_ghcr_tag" "$CI_REGISTRY_IMAGE/wb-redis:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    - crane copy "ghcr.io/quanted/wb-localstack:$wb_localstack_ghcr_tag" "$CI_REGISTRY_IMAGE/wb-localstack:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"

ApiImageScan:
  stage: Image Scan
  tags:
    - twistcli
  when: manual
  variables:
    GIT_STRATEGY: none
  script:
    - 'export PRISMA_CI_TOKEN=$(curl -kH "Content-Type: application/json" -d "{\"username\":\"$prisma_cloud_compute_username\", \"password\":\"$prisma_cloud_compute_password\"}" https://prismacloud.epa.gov/api/v32.01/authenticate | jq -r .token)'
    - 'curl --progress-bar -L -k --header "Authorization: Bearer $PRISMA_CI_TOKEN" https://prismacloud.epa.gov/api/v1/util/twistcli > twistcli; chmod a+x twistcli;'
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE/wb-api:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
    - ./twistcli images scan --address=https://prismacloud.epa.gov --details --token=$PRISMA_CI_TOKEN $CI_REGISTRY_IMAGE/wb-api:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA 
  after_script:
    - rm -rf $CI_PROJECT_DIR

RedisImageScan:
  stage: Image Scan
  tags:
    - twistcli
  when: manual
  variables:
    GIT_STRATEGY: none
  script:
    - 'export PRISMA_CI_TOKEN=$(curl -kH "Content-Type: application/json" -d "{\"username\":\"$prisma_cloud_compute_username\", \"password\":\"$prisma_cloud_compute_password\"}" https://prismacloud.epa.gov/api/v32.01/authenticate | jq -r .token)'
    - 'curl --progress-bar -L -k --header "Authorization: Bearer $PRISMA_CI_TOKEN" https://prismacloud.epa.gov/api/v1/util/twistcli > twistcli; chmod a+x twistcli;'
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE/wb-redis:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
    - ./twistcli images scan --address=https://prismacloud.epa.gov --details --token=$PRISMA_CI_TOKEN $CI_REGISTRY_IMAGE/wb-redis:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA 
  after_script:
    - rm -rf $CI_PROJECT_DIR
