stages:
  - Image Copy


include:
  - project: 'DSO/DASTScanner'
    file: '.gitlab-ci.yml'
  - remote: 'https://gitlab.com/prismacloud-public/shift-left/extension/-/raw/master/.pcs.gitlab-ci.yml'


variables:
  wb_api_tag: image-test-8936e1df989f3003a19b8ab4843dc16a0a8d16a4  # GHCR tag
  wb_redis_tag: gdit-dev
  

CopyDevImages:
  stage: Image Copy
  tags:
    - qed-stg-runner
  when: manual
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [ "" ]
  script:
    - crane auth login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - crane copy "ghcr.io/quanted/wb-api:$wb_api_tag" "$CI_REGISTRY_IMAGE/wb-api:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    - crane copy "ghcr.io/quanted/wb-redis:$wb_redis_tag" "$CI_REGISTRY_IMAGE/wb-redis:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
