stages:
  - Image Copy

include:
  - project: 'DSO/DASTScanner'
    file: '.gitlab-ci.yml'
  - remote: 'https://gitlab.com/prismacloud-public/shift-left/extension/-/raw/master/.pcs.gitlab-ci.yml'
  
CopyDevImages:
  stage: Image Copy
  tags:
    - qed-stg-runner
  when: manual
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [ "" ]
  script:
    - crane auth login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - crane copy "ghcr.io/quanted/wb-flask:${WB_FLASK_IMAGE_TAG:-gdit-dev}" "$CI_REGISTRY_IMAGE/wb-flask:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    - crane copy "ghcr.io/quanted/wb-celery:${WB_CELERY_IMAGE_TAG:-gdit-dev}" "$CI_REGISTRY_IMAGE/wb-celery:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    - crane copy "ghcr.io/quanted/wb-redis:${WB_API_IMAGE_TAG:-gdit-dev}" "$CI_REGISTRY_IMAGE/wb-redis:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
