name: cyan-waterbody
channels:
  - conda-forge
  - defaults
dependencies:
  # - rasterio=1.3.3
  - rasterio
  # - geopandas=0.12.1
  - geopandas
  # - numpy=1.23.4
  - numpy
  - python=3.8
  - celery==5.0.5
  - redis==3.5.3
  # - apscheduler=3.7.0
  - apscheduler
  # - pillow=9.2.0
  - pillow
  - flask=2.2.2
  # - tqdm=4.64.1
  - tqdm
  # - fiona=1.8.22
  - fiona
  # - xhtml2pdf=0.2.8
  - xhtml2pdf
  # - plotly=5.11.0
  - plotly
  # - flask_cors=3.0.10
  - flask_cors
  # - boto3=1.26.9
  - boto3
