#name: cyan-waterbody2
#channels:
#  - conda-forge
#  - defaults
#dependencies:
#  - rasterio
#  - geopandas
#  - numpy=1.23.4
#  - python=3.8
#  - pillow
#  - flask=2.2.2
tqdm=4.64.1
xhtml2pdf=0.2.8
plotly
flask_cors=3.0.10
#boto3=1.26.9
celery=5.0.5
redis=3.5.3
apscheduler=3.6.3
#  - uwsgis