name: cyan-waterbody
channels:
  - conda-forge
  - defaults
dependencies:
  - rasterio=1.3.3
  - geopandas=0.12.1
  - numpy=1.23.4
  - python=3.8
  - pillow=9.2.0
  - flask=2.2.2
  - tqdm=4.64.1
  - fiona=1.8.22
  - xhtml2pdf=0.2.8
  - plotly=5.11.0
  - flask_cors=3.0.10
  - boto3=1.26.9
  - celery
  - redis
