name: cyan-waterbody2
channels:
  - conda-forge
  - defaults
dependencies:
  - rasterio=1.2.10
  - geopandas=0.12.2
  - numpy=1.23.4
  - python=3.8
  - pillow=9.2.0
  - flask=2.2.2
  - tqdm=4.64.1
  - fiona=1.8.21
  - xhtml2pdf=0.2.8
  - plotly=5.11.0
  - flask_cors=3.0.10
  - boto3=1.26.9
  - celery=5.0.5
  - redis=3.5.3
  - apscheduler=3.6.3
  - uwsgi
#  - pyproj=3.4.1
