#FROM python:3.8
FROM python:3.10.12

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV PATH /opt/conda/bin:/opt/conda/envs/env/bin:/opt/mamba/bin:/opt/mamba/envs/env/bin:$PATH

RUN apt-get update --fix-missing
RUN apt-get install -y wget bzip2 ca-certificates \
    libglib2.0-0 libxext6 libsm6 libxrender1 \
    python3-pip software-properties-common build-essential \
    make sqlite3 gfortran python-dev-is-python3 \
    git mercurial subversion

# Python 3.8 miniconda install:
#RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-py38_4.12.0-Linux-x86_64.sh -O ~/miniconda.sh && \
#    /bin/bash ~/miniconda.sh -b -p /opt/conda && \
#    rm ~/miniconda.sh && \
#    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
#    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
#    echo "conda activate base" >> ~/.bashrc
# Python 3.10 minconda install:
# RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-py310_23.5.2-0-Linux-x86_64.sh -O ~/miniconda.sh && \
#     /bin/bash ~/miniconda.sh -b -p /opt/conda && \
#     rm ~/miniconda.sh && \
#     ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
#     echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
#     echo "conda activate base" >> ~/.bashrc

RUN wget "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Linux-x86_64.sh"
RUN /bin/bash Mambaforge-Linux-x86_64.sh -b -p /opt/mamba
RUN rm Mambaforge-Linux-x86_64.sh
#RUN ln -s /opt/mamba/etc/profile.d/mamba.sh /etc/profile.d/mamba.sh
#RUN echo ". /opt/mamba/etc/profile.d/mamba.sh" >> ~/.bashrc
#RUN echo "mamba activate base" >> ~/.bashrc
#RUN sh ~/.bashrc


ARG TINI_VERSION=0.19.0
RUN apt-get install -y curl grep sed dpkg vim && \
    curl -L "https://github.com/krallin/tini/releases/download/v$TINI_VERSION/tini_$TINI_VERSION.deb" > tini.deb && \
    dpkg -i tini.deb && \
    rm tini.deb && \
    apt-get clean

RUN apt update -y && apt install -y --fix-missing --no-install-recommends \
    python3-pip software-properties-common build-essential \
    cmake sqlite3 gfortran python-dev-is-python3

# gdal vesion restriction due to fiona not supporting gdal>2.4.3
ARG GDAL_VERSION=3.7.1
ARG CONDA_ENV="base"



########### MAMBA INSTALL AND SETUP ###########
# RUN conda config --add channels conda-forge
# 
# RUN conda update -n base --all && \
#     conda install -n base mamba

#RUN /opt/mamba/bin/mamba create -n $CONDA_ENV python=3.8 gdal=$GDAL_VERSION -y
###############################################


RUN /opt/mamba/bin/mamba init && \
    /opt/mamba/bin/activate $CONDA_ENV


COPY environment.yml /src/environment.yml
RUN mamba env update -n=$CONDA_ENV -f /src/environment.yml
RUN mamba install -n=$CONDA_ENV -c conda-forge gdal=$GDAL_VERSION -y
RUN mamba install -n=$CONDA_ENV -c conda-forge rasterio fiona -y
RUN mamba install -n=$CONDA_ENV -c conda-forge geopandas -y
RUN mamba install -n=$CONDA_ENV -c conda-forge matplotlib=3.7.0 -y


#RUN conda update conda -y
#RUN conda info

COPY . /src/

RUN chmod 755 /src/start_flask.sh

# Updating Anaconda packages
RUN mamba install -n=$CONDA_ENV -c conda-forge uwsgi -y

COPY uwsgi.ini /etc/uwsgi/uwsgi.ini

WORKDIR /src
EXPOSE 8080

# CMD ["python", "wb_flask.py"]
CMD ["sh", "start_flask.sh"]
