FROM redis:7.2.4-alpine

RUN apk add --upgrade apk-tools
RUN apk upgrade --available

#------ vulnerability fixes ------#
RUN apk del go
COPY --from=tianon/gosu /gosu /usr/local/bin/
RUN find /usr/lib -name *.pem -delete
#---------------------------------#