name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - rasterio=1.3.7
  - geopandas=0.13.2
  - numpy=1.25.2
  - pillow=9.5.0
  - flask=2.3.3
  - tqdm=4.66.1
  - fiona=1.9.4
  - libspatialindex
  - flask-cors=4.0.0
  - xhtml2pdf=0.2.6
  - plotly=5.16.1
  - python-kaleido
  - celery=5.3.4
  - redis=5.0.3
  - APScheduler=3.10.4
  - boto3=1.28.45
  - jinja2=3.1.2
  - uwsgi
  - matplotlib
  - gdal