name: cyan-waterbody
channels:
  - conda-forge
dependencies:
  - rasterio
  - geopandas
  - numpy
  - python=3.8
  - pillow
  - flask=2.2.2
  - tqdm
  - fiona
  - libspatialindex
  - flask-cors
  - xhtml2pdf
  - plotly
  - python-kaleido
  - boto3
  - uwsgi
  - celery==5.0.5
  - redis==3.5.3
  - apscheduler
