name: cyan-waterbody-2
channels:
  - conda-forge
  - defaults
dependencies:
  - rasterio
  - geopandas=0.9.0
  - numpy
  - python=3.9
  - pillow
  - flask=2.2.2
  - tqdm
  - fiona
  - libspatialindex
  - flask-cors
  - xhtml2pdf=0.2.5
  - plotly
  - python-kaleido
  - boto3
  - celery==5.0.5
  - redis==3.5.3
  - apscheduler
  - gdal=3.1.4
