name: cyan-waterbody
channels:
  - conda-forge
  - defaults
dependencies:
#  - rasterio=1.2.0
#  - geopandas=0.9.0
  - numpy
  - pillow
  - flask
  - tqdm=4.59.0
#  - fiona=1.8.18
  - libspatialindex=1.9.3
  - flask-cors=3.0.10
  - xhtml2pdf
  - plotly
  - python-kaleido
  - celery=5.0.5
  - redis=3.5.3
  - APScheduler==3.8.0
  - boto3
  - jinja2<=3.0